### PR TITLE
Update docs in preparation for cli V7 GA

### PR DESCRIPTION
**Pull request by weymanf**
Hi Docs Team. We are preparing to GA cf CLI version 7. We are trying to remove references to any beta tags left behind. This is one of 3 PRs. The others should be in docs-cf-cli, docs-cf-admin.

### CODE REVIEW

**Comment by jncd** [comment]
Nice work! Thank you @weymanf

**Comment by Gerg** [comment]
FYI @heyjcollins

**Comment by jncd** [comment]
Hi @belinda-liu and @weymanf 
I'm a bit late getting back to reviewing and cherry-picking all these updates. I'm tweaking the subnavs to remove the (Beta)'s.
One quick question: Is Pushing Apps with Sidecar Processes still in beta? 
Screen Shot 2020-05-19 at 4 12 59 PM

**Comment by Gerg** [comment]
Based on [slack discussion](https://cloudfoundry.slack.com/archives/CBNDLQBB5/p1588888916198600), it looks like sidecars are no longer experimental.

cc @ssisil @selzoc

**Comment by jncd** [comment]
Thanks!  I'll remove the (Beta)'s on that title and subnav.

**Pull request merged**
