### PR TITLE
Update ssh-apps.html.md.erb

### PR DESCRIPTION
**Pull request by mattiaongit**
Adding additional and easier command to transfer a file.

### CODE REVIEW

**Comment by ljarzynski** [comment]
Hi @mattiaongit ! Thank you for contributing. Please see the comment from Gitbot above. Once you have your CLA, I can merge the PR.

**Comment by mattiaongit** [comment]
Hello Landon,

I've now submitted my signed CLA. Shoud I reopen the PR?

Il giorno ven 19 lug 2019 alle ore 20:54 Landon Jarzynski <
notifications@github.com> ha scritto:

**Comment by mattiaongit** [comment]
CLA is in place now

**Comment by mlimonczenko** [comment]
Thank you, @mattiaongit!

**Pull request merged**
