### PR TITLE
Update manifest.html.md.erb

### PR DESCRIPTION
**Pull request by TimGerlach**
Add effect of random-route option in conjunction with host and routes

### CODE REVIEW

**Comment by TimGerlach** [comment]
Hi @dkoper,
as discussed, here's the updated documentation for the ``random-route`` option. Feel free to edit.

Cheers,
Tim

**Comment by ljarzynski** [comment]
Hey @TimGerlach! I'm a tech writer for CF docs am reviewing the PR. Was wondering if this rewording makes sense to you: 

The cf CLI ignores the `random-route` option if the command entered contains a `host` property. You can use the `random-route` option with the `routes` command, however. In this case, the cf CLI creates a `random-route` and ignores all other routes.

**Comment by TimGerlach** [comment]
Hi @ljarzynski,

almost, ``host`` and ``routes`` are properties in the deployment manifest and not part of the command.

**Comment by dkoper** [comment]
@ljarzynski Why is "random-route" formatted like that in your last sentence? I'd take `random-route` to refer to the app manifest attribute, and that is not what's being created here.

It may be easier to understand if we explain the intent, not (just) the restrictions:
When pushing an app without specifying any route related CLI options or app manifest flags, the CLI will try to generate a route based on the app name. This could cause collisions.   
Use the `random-route` attribute in that situation to generate a unique route, one that includes the app name and random words in case of an HTTP route, or an available unused port number in case of a TCP route.  
This attribute is particularly useful when developing an app manifest for a classroom training exercise, where multiple people will try to deploy the same app to the same space.
You can also use this attribute to randomize routes declared with the `route` attribute in the app manifest, which can be useful to avoid route collisions while deploying the same app to multiple spaces for testing purposes.

**Comment by ljarzynski** [comment]
Thanks @TimGerlach and @dkoper for the feedback! I'm working on a branch with some edits and will incorporate. Dies -- think I just formatted it as `random-route` because I was referencing the command. But I suppose in that context plain old "random route" does the trick :)

**Comment by TimGerlach** [comment]
@dkoper +1, I like the positively formulated approach.

@ljarzynski: Thanks so much for incorporating and taking the time to edit. I appreciate that the docs are observed carefully to constantly strive to keep the documentation in such a high quality.

**Comment by dkoper** [comment]
@ljarzynski Some issues with the current text:
- `cf CLI generates a route depending on the protocol`: I don't think "protocol" is the right word: you could use a TCP route because you want HTTPS traffic to be terminated at your app, instead of the Gorouter. *I've submitted a PR with an alternative.*
- `The command line option that corresponds to this attribute is --random-route.`: it corresponds *and overwrites*, and the overwriting is useful for the user to know. *Sent in a PR.*
- `The cf CLI ignores random-route if the app manifest contains the host attribute. `: same for "hosts" attribute.
   "routes" and "host"/"hosts" cannot be declared together (CLI validates), hence my suggestion for a positively formulated approach focusing what it does to routes that are not declared, or declared using "routes". The current note to me reads as "ignore", "however", "ignore". *No PR submitted, I assume you have conventions on Notes?*
- `In this case, the cf CLI creates a random route and ignores all other routes.` (in the Note): Note the CLI creates a route for *each* route declared by the 'route' attribute in the app manifest (hence my use of the singular `route` in the previous comment). For HTTP routes, it randomises the host part, for TCP routes it randomises the port number. The current text seems to suggest it will create only one route and ignore all existing route declarations. *No PR submitted.*

**Comment by ljarzynski** [comment]
@dkoper Thank you for this valuable feedback! For the points for which you have not submitted a PR, I will go ahead work on an alternative today and ping you to see what you think.

**Comment by ljarzynski** [comment]
@dkoper Also I didn't see a PR for your first bullet point... perhaps you made the changed locally and didn't submit! Would love to get your alternative in there!

**Comment by dkoper** [comment]
@ljarzynski Nothing fancy: #169.

Actually, I wonder if we can be less verbose about how the random routes are created. The user just wants a unique route:

---

You can use the `random-route` attribute to generate a unique route and avoid name collisions.  
When you use `random-route`, the cf CLI generates an HTTP route with a random host (if `host` not set) or a TCP route with an unused port number.

~~You can use the random-route attribute to generate a unique route and avoid name collisions. When you use random-route, the cf CLI generates a route depending on the protocol:~~

~~HTTP: The random route consists of the app name and random words.~~
~~TCP: The random route consists of an unused port number.~~

---

And then we can delete the note.

I'll submit another PR.

**Comment by ljarzynski** [comment]
Awesome! Thanks so much for your help on this @dkoper! Always great to have a subject matter expert who wants to get the words right :)

**Comment by dkoper** [comment]
Yw, nice to see the article evolve with each iteration.
Thanks again @TimGerlach for initiating this. Looking forward to your next contribution.

**Pull request merged**
