### PR TITLE
Update routes and domains docs for Service Discovery GA

### PR DESCRIPTION
**Pull request by christianang**
Please, don't pull this PR in quite yet. There are still a few more stories to do before Service Discovery is GA and we would want this PR to be merged after it is GA. We will let you know when it can be merged.

Thanks.

### CODE REVIEW

**Comment by pspinrad** [comment]
@christianang -- going thru old "don't merge yet" PRs, wondering about this one-- thanks!

**Comment by christianang** [comment]
This can be merged. Sorry for dropping the ball, I thought this had been merged.

**Comment by christianang** [comment]
Previously only checked this out on my phone and didn't notice the conflicts. I'll fix the PR too.

**Comment by christianang** [comment]
Looking through the current version of the docs it looks like it is already up to date. Closing this. Sorry for the confusion.

**Pull request closed without merging**
