### PR TITLE
add Sematext Logsene to third-party log management

### PR DESCRIPTION
**Pull request by megastef**

### CODE REVIEW

**Comment by abbyachau** [comment]
Thanks, @megastef!

**Comment by abbyachau** [comment]
Hi @megastef, many thanks for your contribution. We've reopened this issue because accepting these commits requires you to have a CLA on file with us. Please could you review the instructions above regarding this. Once you've signed a CLA, we'll review your request again. Thanks!

Looking forward to hearing from you,

Abby

**Comment by otisg** [comment]
@abbyachau @megastef - we've submitted the corporate CLA earlier today

**Comment by bentarnoff** [comment]
@megastef Great, thanks. The Cloud Foundry Foundation will process the CLA and add you to the relevant organization. If the organization does not appear on your GitHub profile, please follow the instructions here: https://help.github.com/articles/publicizing-or-hiding-organization-membership/. Once your membership is public, I can reopen this PR.

**Comment by otisg** [comment]
@bentarnoff how do we know when CFF has processed the CLA?

**Comment by bentarnoff** [comment]
@otisg Sorry for the delay. I've just checked with our staff and it appears Sematext does not appear on the list of companies that have signed the CLA. We recommend getting in touch with the Cloud Foundry Foundation directly to inquire about the status of your CLA. Thanks!

**Comment by chipchilders** [comment]
@bentarnoff we have the CLA.. the bots have been updated (pending their auto-deploy). Feel free to proceed with merging this!

**Comment by bentarnoff** [comment]
@chipchilders Great, thanks! Merging now.

**Comment by bentarnoff** [comment]
@megastef @otisg Your content has been merged, with a few light edits for readability. You should be able to see it in the repo now. Thanks!

**Pull request merged**
