### PR TITLE
Remove note about Java pre-runtime hooks

### PR DESCRIPTION
**Pull request by forbushbl**
I just tested using a .profile with Java buildpack v4.17.2 and it works fine. Perhaps this was an old restriction that has been fixed?

### CODE REVIEW

**Comment by bentarnoff** [comment]
Thanks @forbushbl. @nebhale can you confirm?

**Comment by nebhale** [comment]
I do not know what a pre-runtime hook is, and therefore have no informed opinion on this change.

**Comment by bentarnoff** [comment]
@sclevine Any thoughts on the above?

**Comment by forbushbl** [comment]
@nebhale and @sclevine When I say "pre-runtime hook" I mean a .profile script. I've confirmed that this is still working as of v4.19.1. If I put the following .profile script in the root of my jar file.

```bash
#!/bin/bash
echo "stuff" > /home/vcap/somefile
```

Then push my app

```bash
cf push demo-app -b https://github.com/cloudfoundry/java-buildpack.git#v4.19.1 -p target/app.jar
```
Then when I ssh into my instance, I see the file created

```
vcap@69389e4a-d58a-488b-62b1-7945:~$ ls -l
total 8
drwxr-xr-x 1 vcap vcap  88 Jun 18 21:23 app
drwxr-xr-x 3 vcap vcap  15 Jun 18 21:23 deps
drwxr-xr-x 2 vcap vcap   6 Jun 18 21:23 logs
drwxr-xr-x 2 vcap vcap   6 Jun 18 21:23 profile.d
-rw-r--r-- 1 vcap vcap   6 Jun 18 21:23 somefile <-----------
-rw-r--r-- 1 vcap vcap 923 Jun 18 21:23 staging_info.yml
drwxr-xr-x 4 vcap vcap  92 Jun 18 21:23 tmp
```

**Comment by paigecalvert** [comment]
Hi @forbushbl, we're checking in on old PRs. Looks like this note was clarified in the following commit about 6 months ago, so we're going to close out this PR: https://github.com/cloudfoundry/docs-dev-guide/commit/31b2bcf0c267b8199fef7830660f406ba2f0e0b7

Feel free to reach back out if you have concerns, and thanks again for your contribution!

**Pull request closed without merging**
