### PR TITLE
Add docs for named service bindings

### PR DESCRIPTION
**Pull request by Gerg**
Tracker story here: https://www.pivotaltracker.com/story/show/143843317

Please do not merge until approved by @zrob

### CODE REVIEW

**Comment by zrob** [comment]
looks good!

**Comment by apeek4** [comment]
Hi @Gerg and @zrob, should this change be backported to earlier active versions or is this change specific to 2.2? Thanks!

**Comment by zrob** [comment]
@apeek4 good call! this can be added to 2.1

**Comment by apeek4** [comment]
@zrob Great, I will get these changes into 2.1 today

**Pull request merged**
