### PR TITLE
Remove obsolete NFS mount warnings

### PR DESCRIPTION
**Pull request by davewalter**
[#159441838](https://www.pivotaltracker.com/story/show/159441838)

Please let us know if you have any questions.
@mariash and Dave

### CODE REVIEW

**Comment by ljarzynski** [comment]
Thanks @davewalter and @mariash !

**Comment by julian-hj** [comment]
@ljarzynski yeah the change can be applied to all branches.  The fix was in garden-runc-release 1.3.0 & nfs-volume-release 1.2.1, and has been backported to all the supported versions of PCF.

**Comment by pspinrad** [comment]
Hey @davewalter @mariash -- should we also delete the similar note further down?
https://github.com/cloudfoundry/docs-dev-guide/blob/master/services/_using-vol-services.html.md.erb#L117

**Comment by julian-hj** [comment]
@pspinrad yes absolutely.  Thanks!

**Comment by pspinrad** [comment]
@julian-hj done!

**Pull request merged**
