### PR TITLE
Add logit-io log drain documentation

### PR DESCRIPTION
**Pull request by firegrass**
[Logit](https://logit.io) is a hosted ELK service and is compatible with Cloud Foundry log drains.

cc @mrdavidlaing

### CODE REVIEW

**Comment by firegrass** [comment]
CLA completed with @mrdavidlaing yesterday, please close and re-open. Cheers.

**Comment by ljarzynski** [comment]
Hi @firegrass, thanks for completing the CLA. I tried closing and re-opening, and we still get the same message from dredd. Are you able to publicize your membership? If not, we may have to wait a little longer for the CLA to "register".

**Comment by leesmith110** [comment]
@ljarzynski we had signed the CLA, i have a copy if you need?

I can also confirm @firegrass and myself have public memberships, can you retry?

**Comment by ljarzynski** [comment]
Thanks, @firegrass!

**Pull request merged**
