### PR TITLE
Service instance sharing is now GA

### PR DESCRIPTION
**Pull request by mattmcneeney**
The service instance sharing feature is now Generally Available!

### CODE REVIEW

**Comment by mattmcneeney** [comment]
Please hold off from merging this until we add a message here saying that this is in a CF deployment (should be soon!).

**Comment by mattmcneeney** [comment]
This feature is now in a cf-deployment so can be merged! Thanks!

**Comment by lurraca** [comment]
We are blocked on announcing that this feature is GA since the docs still label it as `BETA`. As soon as the PR is merged we would announce the feature to a broader audience.

@cloudfoundry/services-api

**Comment by ljarzynski** [comment]
@lurraca @mattmcneeney Thanks! And sorry for the slight delay. I have merged and the changes should be reflected on the production site withing 10-15 min from merging

**Comment by Samze** [comment]
@ljarzynski Thanks a bunch!

**Pull request merged**
