### PR TITLE
Correct directory name is profile.d

### PR DESCRIPTION
**Pull request by mchelen**

### CODE REVIEW

**Comment by seviet** [comment]
hi @mchelen! thank you so much for this PR! please sign the CLA or publicize your membership with an org that has signed the corporate CLA! after you've completed that. we can merge. thanks!!

**Comment by emalm** [comment]
Hey, @sclevine,

Is it correct that nowadays buildpack-app droplets may have the buildpack-specified profile scripts either in the older `/home/vcap/app/.profile.d` and in the newer `/home/vcap/profile.d`? That's my reading of https://github.com/cloudfoundry/buildpackapplifecycle/blob/1e1fa5ae3fdb39bf974fe111ce2e7373473550fc/launcher/launcher_unix.go#L13-L23, anyway. If so, there might be some other changes required to this documentation page than just those in this PR.

Thanks,
Eric

**Comment by mchelen** [comment]
Yeah I was digging into this a bit, and it does seem there are some more complications. For example, `DEPS_DIR` needs to be set before executing profile.d scripts.

**Comment by sclevine** [comment]
The supported way to get a shell with the same environment as the app is to run:
```
/tmp/lifecycle/shell
```
This should eventually be exposed as a cf CLI argument to avoid exposing `/tmp/lifecycle` to the user, but it's the best solution right now.

Note that this doesn't source the app's `.profile` file, only the contents of `/home/vcap/profile.d` and the deprecated `/home/vcap/app/.profile.d`. This is to prevent non-idempotent stuff in `.profile` from running again and crashing the app (even though we encourage app devs to make `.profile` idempotent).

`/home/vcap/app/profile.d` is not part of the contract.

**Comment by mchelen** [comment]
@sclevine Ah ok, so should the docs be updated to simply say "Run `/tmp/lifecycle/shell`" for now?

**Comment by sclevine** [comment]
That seems like the best solution to me.

**Comment by pspinrad** [comment]
@mchelen cleaning up old docs PRs -- so for this one, we should just add a "Run `/tmp/lifecycle/shell`" step before the `profile.d` loop command here? https://docs.pivotal.io/pivotalcf/2-3/devguide/deploy-apps/ssh-apps.html#ssh-env  Thanks!

**Comment by mchelen** [comment]
My understanding is that the loop isn't even needed, simply running the one
`/tmp/lifecycle/shell` script is enough the load the correct environment.
That's what I've been doing when sshing into a nodejs app and then I'm able
to execute node and npm.

**Pull request closed without merging**
