### PR TITLE
Update to include TLS

### PR DESCRIPTION
**Pull request by leesmith110**
Updated the docs to include the TLS option

### CODE REVIEW

**Comment by leesmith110** [comment]
I can confirm we have already signed the CLA and have publicized our membership

**Comment by seviet** [comment]
Hi @leesmith110! Thanks for the PR! Could you verify the name of the org that signed the CLA? I'm afraid I didn't find the two orgs published on your profile in our CLA list.

**Comment by leesmith110** [comment]
Hey,

It could be Logit.io or Smith Software Ltd

Regards,

Lee

**Comment by leesmith110** [comment]
@seviet Not sure if you seen my comment above?

**Comment by seviet** [comment]
I didn't! Thanks for pinging me again. I am rechecking with admins on those orgs.

**Comment by seviet** [comment]
Hi @leesmith110! I'm sorry to report that our admins have no record of a CLA for either of those orgs. Could I trouble you to resubmit a signed CLA with your github username to contributors@cloudfoundry.org? If resubmitting an org CLA, please also verify that the org with signed CLA is publicized on your GitHub profile. Thanks for your patience, and thank you for making our docs better!

**Comment by cf-pub-tools** [comment]
Hi @leesmith110!
This pull request has had no activity since Feb 2.
Unfortunately, we still have no record of you, or either Logit.io or Smith Software Ltd having signed a CLA with us. Because we cannot accept any pull request, no matter how small, without a signed CLA, we regretfully must close this PR.

Please let us know when we can review a signed CLA so we can re-open and accept this PR.

**Comment by leesmith110** [comment]
Hi,

We have resubmitted and sent the signed CLA (Chris Clark) has responded.

Can we reopen?

Regards,

Lee

**Pull request closed without merging**
